on: [pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    name: Basic Checks
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.1.7

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
